CREATE TABLE IF NOT EXISTS t_categorie (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nomAR VARCHAR(50) DEFAULT NULL,
	nomFR VARCHAR(50) DEFAULT NULL,
	longueur DECIMAL(12,2) DEFAULT NULL,
	largeur DECIMAL(12,2) DEFAULT NULL,
	hauteur DECIMAL(12,2) DEFAULT NULL,
	diametre DECIMAL(12,2) DEFAULT NULL,
	forme VARCHAR(50) DEFAULT NULL,
	couleur VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;