CREATE TABLE IF NOT EXISTS t_client (
	id INT(11) NOT NULL AUTO_INCREMENT,
	code VARCHAR(50) DEFAULT NULL,
	matricule VARCHAR(50) DEFAULT NULL,
	nom VARCHAR(100) DEFAULT NULL,
	cin VARCHAR(50) DEFAULT NULL,
	ville VARCHAR(50) DEFAULT NULL,
	telephone VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;