CREATE TABLE IF NOT EXISTS t_factureDetails (
	id INT(11) NOT NULL AUTO_INCREMENT,
	designation VARCHAR(100) DEFAULT NULL,
	quantite DECIMAL(12,2) DEFAULT NULL,
	prixUnitaire DECIMAL(12,2) DEFAULT NULL,
	idFacture INT(11) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;