CREATE TABLE IF NOT EXISTS t_produit (
	id INT(11) NOT NULL AUTO_INCREMENT,
	dimension DECIMAL(12,2) DEFAULT NULL,
	diametre DECIMAL(12,2) DEFAULT NULL,
	forme VARCHAR(50) DEFAULT NULL,
	prixAchat DECIMAL(12,2) DEFAULT NULL,
	prixVente DECIMAL(12,2) DEFAULT NULL,
	prixVenteMin DECIMAL(12,2) DEFAULT NULL,
	quantite DECIMAL(12,2) DEFAULT NULL,
	poids DECIMAL(12,2) DEFAULT NULL,
	code INT(12) DEFAULT NULL,
	idCategorie INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;