CREATE TABLE IF NOT EXISTS t_sale (
	id INT(11) NOT NULL AUTO_INCREMENT,
	quantity DECIMAL(12,2) DEFAULT NULL,
	price DECIMAL(12,2) DEFAULT NULL,
	discount DECIMAL(12,2) DEFAULT NULL,
	total DECIMAL(12,2) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;